### ISSUE TITLE
Cbc solver fails to build on Windows

### ISSUE THREAD

**Issue by haydenfree** [heileman/CurricularAnalytics.jl#11]
The Cbc package will not build on Windows and thus prevents the toolbox from working correctly.

Potentially look for an alternative or work to make it compatible.

**Comment by orhanabar** [comment]
I found a solution for that. The error is about finding a file in WinRPM package so when you change the file name 
"mingw64-libstdc++6-8.2.0-2.1.noarch.cpio" to
"mingw64-libstdc%2B%2B6-8.2.0-2.3.noarch.cpio" in 
C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\cache\2 folder it builds fine.

**Comment by orhanabar** [comment]
They have fixed this issue and it builds on Windows fine.
